// Code generated by Thrift Compiler (0.19.0). DO NOT EDIT.

package hygrothermograph

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"regexp"
	"strings"
	"time"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = errors.New
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal

// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

// Attributes:
//  - Humidity
//  - Temperature
type Hygrothermograph struct {
	Humidity    *float64 `thrift:"Humidity,1" db:"Humidity" json:"Humidity,omitempty"`
	Temperature *float64 `thrift:"Temperature,2" db:"Temperature" json:"Temperature,omitempty"`
}

func NewHygrothermograph() *Hygrothermograph {
	return &Hygrothermograph{}
}

var Hygrothermograph_Humidity_DEFAULT float64

func (p *Hygrothermograph) GetHumidity() float64 {
	if !p.IsSetHumidity() {
		return Hygrothermograph_Humidity_DEFAULT
	}
	return *p.Humidity
}

var Hygrothermograph_Temperature_DEFAULT float64

func (p *Hygrothermograph) GetTemperature() float64 {
	if !p.IsSetTemperature() {
		return Hygrothermograph_Temperature_DEFAULT
	}
	return *p.Temperature
}
func (p *Hygrothermograph) IsSetHumidity() bool {
	return p.Humidity != nil
}

func (p *Hygrothermograph) IsSetTemperature() bool {
	return p.Temperature != nil
}

func (p *Hygrothermograph) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.DOUBLE {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.DOUBLE {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *Hygrothermograph) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadDouble(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Humidity = &v
	}
	return nil
}

func (p *Hygrothermograph) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadDouble(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Temperature = &v
	}
	return nil
}

func (p *Hygrothermograph) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "Hygrothermograph"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Hygrothermograph) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetHumidity() {
		if err := oprot.WriteFieldBegin(ctx, "Humidity", thrift.DOUBLE, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:Humidity: ", p), err)
		}
		if err := oprot.WriteDouble(ctx, float64(*p.Humidity)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.Humidity (1) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:Humidity: ", p), err)
		}
	}
	return err
}

func (p *Hygrothermograph) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetTemperature() {
		if err := oprot.WriteFieldBegin(ctx, "Temperature", thrift.DOUBLE, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:Temperature: ", p), err)
		}
		if err := oprot.WriteDouble(ctx, float64(*p.Temperature)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.Temperature (2) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:Temperature: ", p), err)
		}
	}
	return err
}

func (p *Hygrothermograph) Equals(other *Hygrothermograph) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Humidity != other.Humidity {
		if p.Humidity == nil || other.Humidity == nil {
			return false
		}
		if (*p.Humidity) != (*other.Humidity) {
			return false
		}
	}
	if p.Temperature != other.Temperature {
		if p.Temperature == nil || other.Temperature == nil {
			return false
		}
		if (*p.Temperature) != (*other.Temperature) {
			return false
		}
	}
	return true
}

func (p *Hygrothermograph) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Hygrothermograph(%+v)", *p)
}

func (p *Hygrothermograph) Validate() error {
	return nil
}

type HygrothermographService interface {
	GetHygrothermograph(ctx context.Context) (_r *Hygrothermograph, _err error)
}

type HygrothermographServiceClient struct {
	c    thrift.TClient
	meta thrift.ResponseMeta
}

func NewHygrothermographServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *HygrothermographServiceClient {
	return &HygrothermographServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewHygrothermographServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *HygrothermographServiceClient {
	return &HygrothermographServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewHygrothermographServiceClient(c thrift.TClient) *HygrothermographServiceClient {
	return &HygrothermographServiceClient{
		c: c,
	}
}

func (p *HygrothermographServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *HygrothermographServiceClient) LastResponseMeta_() thrift.ResponseMeta {
	return p.meta
}

func (p *HygrothermographServiceClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
	p.meta = meta
}

func (p *HygrothermographServiceClient) GetHygrothermograph(ctx context.Context) (_r *Hygrothermograph, _err error) {
	var _args0 HygrothermographServiceGetHygrothermographArgs
	var _result2 HygrothermographServiceGetHygrothermographResult
	var _meta1 thrift.ResponseMeta
	_meta1, _err = p.Client_().Call(ctx, "getHygrothermograph", &_args0, &_result2)
	p.SetLastResponseMeta_(_meta1)
	if _err != nil {
		return
	}
	if _ret3 := _result2.GetSuccess(); _ret3 != nil {
		return _ret3, nil
	}
	return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "getHygrothermograph failed: unknown result")
}

type HygrothermographServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      HygrothermographService
}

func (p *HygrothermographServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *HygrothermographServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *HygrothermographServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewHygrothermographServiceProcessor(handler HygrothermographService) *HygrothermographServiceProcessor {

	self4 := &HygrothermographServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self4.processorMap["getHygrothermograph"] = &hygrothermographServiceProcessorGetHygrothermograph{handler: handler}
	return self4
}

func (p *HygrothermographServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
	if err2 != nil {
		return false, thrift.WrapTException(err2)
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(ctx, thrift.STRUCT)
	iprot.ReadMessageEnd(ctx)
	x5 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
	x5.Write(ctx, oprot)
	oprot.WriteMessageEnd(ctx)
	oprot.Flush(ctx)
	return false, x5

}

type hygrothermographServiceProcessorGetHygrothermograph struct {
	handler HygrothermographService
}

func (p *hygrothermographServiceProcessorGetHygrothermograph) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err6 error
	args := HygrothermographServiceGetHygrothermographArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "getHygrothermograph", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := HygrothermographServiceGetHygrothermographResult{}
	if retval, err2 := p.handler.GetHygrothermograph(ctx); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		if errors.Is(err2, thrift.ErrAbandonRequest) {
			return false, thrift.WrapTException(err2)
		}
		if errors.Is(err2, context.Canceled) {
			if err := context.Cause(ctx); errors.Is(err, thrift.ErrAbandonRequest) {
				return false, thrift.WrapTException(err)
			}
		}
		_exc7 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing getHygrothermograph: "+err2.Error())
		if err2 := oprot.WriteMessageBegin(ctx, "getHygrothermograph", thrift.EXCEPTION, seqId); err2 != nil {
			_write_err6 = thrift.WrapTException(err2)
		}
		if err2 := _exc7.Write(ctx, oprot); _write_err6 == nil && err2 != nil {
			_write_err6 = thrift.WrapTException(err2)
		}
		if err2 := oprot.WriteMessageEnd(ctx); _write_err6 == nil && err2 != nil {
			_write_err6 = thrift.WrapTException(err2)
		}
		if err2 := oprot.Flush(ctx); _write_err6 == nil && err2 != nil {
			_write_err6 = thrift.WrapTException(err2)
		}
		if _write_err6 != nil {
			return false, thrift.WrapTException(_write_err6)
		}
		return true, err
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "getHygrothermograph", thrift.REPLY, seqId); err2 != nil {
		_write_err6 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err6 == nil && err2 != nil {
		_write_err6 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err6 == nil && err2 != nil {
		_write_err6 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err6 == nil && err2 != nil {
		_write_err6 = thrift.WrapTException(err2)
	}
	if _write_err6 != nil {
		return false, thrift.WrapTException(_write_err6)
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

type HygrothermographServiceGetHygrothermographArgs struct {
}

func NewHygrothermographServiceGetHygrothermographArgs() *HygrothermographServiceGetHygrothermographArgs {
	return &HygrothermographServiceGetHygrothermographArgs{}
}

func (p *HygrothermographServiceGetHygrothermographArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err := iprot.Skip(ctx, fieldTypeId); err != nil {
			return err
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *HygrothermographServiceGetHygrothermographArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "getHygrothermograph_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *HygrothermographServiceGetHygrothermographArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HygrothermographServiceGetHygrothermographArgs(%+v)", *p)
}

// Attributes:
//  - Success
type HygrothermographServiceGetHygrothermographResult struct {
	Success *Hygrothermograph `thrift:"success,0" db:"success" json:"success,omitempty"`
}

func NewHygrothermographServiceGetHygrothermographResult() *HygrothermographServiceGetHygrothermographResult {
	return &HygrothermographServiceGetHygrothermographResult{}
}

var HygrothermographServiceGetHygrothermographResult_Success_DEFAULT *Hygrothermograph

func (p *HygrothermographServiceGetHygrothermographResult) GetSuccess() *Hygrothermograph {
	if !p.IsSetSuccess() {
		return HygrothermographServiceGetHygrothermographResult_Success_DEFAULT
	}
	return p.Success
}
func (p *HygrothermographServiceGetHygrothermographResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *HygrothermographServiceGetHygrothermographResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *HygrothermographServiceGetHygrothermographResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	p.Success = &Hygrothermograph{}
	if err := p.Success.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *HygrothermographServiceGetHygrothermographResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "getHygrothermograph_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *HygrothermographServiceGetHygrothermographResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *HygrothermographServiceGetHygrothermographResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HygrothermographServiceGetHygrothermographResult(%+v)", *p)
}
