git tag transport/activemq/v1.2.22 --force
git tag transport/asynq/v1.2.28 --force
git tag transport/fasthttp/v1.2.22 --force
git tag transport/gin/v1.2.22 --force
git tag transport/gozero/v1.2.22 --force
git tag transport/graphql/v1.2.22 --force
git tag transport/hertz/v1.2.22 --force
git tag transport/http3/v1.2.22 --force
git tag transport/iris/v1.2.22 --force
git tag transport/kafka/v1.2.22 --force
git tag transport/machinery/v1.2.22 --force
git tag transport/mqtt/v1.2.22 --force
git tag transport/nats/v1.2.22 --force
git tag transport/nsq/v1.2.22 --force
git tag transport/pulsar/v1.2.22 --force
git tag transport/rabbitmq/v1.2.22 --force
git tag transport/redis/v1.2.22 --force
git tag transport/rocketmq/v1.2.22 --force
git tag transport/signalr/v1.2.22 --force
git tag transport/socketio/v1.2.22 --force
git tag transport/sse/v1.2.22 --force
git tag transport/tcp/v1.2.22 --force
git tag transport/thrift/v1.2.22 --force
git tag transport/websocket/v1.2.22 --force
git tag transport/webtransport/v1.2.22 --force
git tag transport/trpc/v1.2.22 --force

git tag transport/keepalive/v1.0.3 --force

git push origin --tags
